### ISSUE TITLE
[page] 参加する

### ISSUE THREAD

**Issue by nekomatu** [DeFiGeek-Community/landing-page#16]
- [ ] 日本語 - https://dfgc-preview.netlify.app/signup/
- [ ] English

### Join

ja
```
DeFiGeek Communityでは様々な分野でのコントリビュータを求めています。詳細な募集条件は DeFiGeekドキュメント を参照ください。

開発者
  - スマートコントラクト開発
  - Web3フロントエンド開発
デザイナー
  - Webデザイン
  - イラストレーター
  - インフォグラフィック
財務
広報
  - ウェブサイト制作
  - 翻訳
  -ガイドブック作成
  - 記事執筆
 
コミュニティでは、上記の分野で細かなタスクまで分けて公募を行っています。メンバーの一部として貢献できるものがあれば自由にご参加ください。詳細はDiscordの「タスク部屋」をご覧ください。
```

en
```
```

章立て毎に以下のテンプレを埋めてください。

ja
```

```

en
```
```

**Comment by nekomatu** [comment]
### ページ名
signup というよりは、join の方が広く使われていてフレンドリーです。
signup は雇用関係をがっつり結ぶ、軍に入隊するといった厳格な印象があります。

### キャッチー

> 日本を代表するDeFi Dapps開発チームに参加してみませんか？

個人的には代表というのは自分たちで述べるもので無く実績に基づいて言われるものだと感じています。立ち上げ期の私たちが言うのはチープに感じました。

いくつかの案
・報酬設定のあるDeFi Dapps開発チームに参加してみませんか？
・オープンソース型コミュニティでDeFi Dappsに携わってみませんか？
・DeFi Dapps開発と成功には多様なスキルと人材が必要です

### 本文

> 詳細な募集条件は DeFiGeekドキュメント を参照ください。

いくつかフローは固まっているもののケースバイケースで裁いているシーンも多いです。
この一文は冒頭からは消してしまってよいでしょう。

> コミュニティでは、上記の分野で細かなタスクまで分けて公募を行っています。メンバーの一部として貢献できるものがあれば自由にご参加ください。詳細はDiscordの「タスク部屋」をご覧ください。

ブラッシュアップしてみました。

案）
コミュニティの成長と成功のためのアクションアイテムを「タスク」と呼んでいます。メンバーは、作成されているタスクに名乗り上げて着手するほか、提案することも期待されています。詳細はDiscord にご参加ください。

**Comment by nekomatu** [comment]
@haruketh 

こちら提案に意見がなければプルリクエストを作成して変更。その後に投票準備を進めたいと思います。
何かありましたらコメントください。

**Comment by nekomatu** [comment]
了解しました。それでは進めていきます。

窓口に関する諸々はとても良いと思いました。

**Comment by nekomatu** [comment]
Discordへのリンクが抜けている。
トップページにあるような分かりやすい大きめボタンを置きたいところ。
Discordファーストなコミュニティになってしまっているが、それは少しずつ変えていきたいという話もあり #7 で検討している。思案する要素はありそうだ。

また、別観点だとこのページへの導線が現在やや乏しい感じがある。

**Comment by haruketh** [comment]
ボタン追加しました。色濃いめ。
https://6166e155ea89e2000777b61b--dfgc-preview.netlify.app/join/
