### ISSUE TITLE
code of conductを定める

### ISSUE THREAD

**Issue by 0xTwo** [DeFiGeek-Community/landing-page#34]
- いわゆる"code of conduct"。価値観や行動規範を示したもの。
- リポジトリ単体で必要な規範よりもコミュニティ全体で定める割合の方が大きそう
  - もしかしたらコミュニティサイトへのリンクでいいかも？
- 投票にかける

参考: OSSガイドラインの「行動規範」 https://opensource.guide/ja/code-of-conduct/
参考: コミュニティサイトの「join」 https://defigeek.xyz/join/

**Comment by 0xTeaTwo** [comment]
yamato-interfaceで用意することではなかったので、イシューの所属するリポジトリをlanding-pageに移動した。

**Comment by haruketh** [comment]
ポジティブな方のCoCをAboutページに追加しました。
https://sleepy-williams-82ba03.netlify.app/about/

**Comment by haruketh** [comment]
大先生対策のCoCをGitbookにドラフトで書きました。レビュワー権限ないと見れないかも。
それと「DFGCコミュニティの概要」ページといくらか重複するので、それをうまいこと行動規範の方に移したいなと。

**Comment by haruketh** [comment]
Gitbookで、Draftをパブリックに表示できない。投票者全員をインバイトするのは無理がある。そのため公開状態で投票にかけ、投票が終わるまで「⚠️本ページは投票中でありドラフト版の扱いです。」と明記する。

**Comment by haruketh** [comment]
Gitbookのドラフトが完成しました。投票前に一次レビューお願いします。
- 「推奨されること・されないこと」はコミュニティへ概要ページから転記してます。投票可決後に、コミュニティ概要ページにはリンクだけ残して削除する
- 違反があったときはコミュニティモデレーターが勇気をもって評価する
- 違反報告は、DiscordでモデレータにDM

**Comment by haruketh** [comment]
事前レビューが終わったのでDiscordで投票かけます。

- ミッション (Aboutページ)
https://sleepy-williams-82ba03.netlify.app/about/

- 行動規範 (Docs)
https://docs.defigeek.xyz/xp7tYlyKF42wcC5xFLyV/code-of-conduct

**Comment by haruketh** [comment]
パブリッシュed
- https://defigeek.xyz/about/
- https://docs.defigeek.xyz/code-of-conduct
- Docsにて、行動規範ページを新たに公開したため「DFGCコミュニティの概要」の「推奨されること、されないこと」欄は、行動規範ページのリンクに置き換えた。
https://github.com/DeFiGeek-Community/defigeek-docs/commit/51f6029872a1f045c9e63691a4886a14a3589833
